default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: 
  pool: 5
  host: localhost

development:
  <<: *default
  database: PIRIS_development

test:
  <<: *default
  database: PIRIS_test

production:
  <<: *default
  database: PIRIS_production

staging:
  <<: *default
  database: PIRIS_staging
